### ISSUE TITLE
Fix test

### ISSUE THREAD

**Issue by Augustyn** [darkonion/SortingComparator#3]
Please fix tests. Should all pass and finish correctly

https://github.com/darkonion/SortingComparator/blob/efc4a159a739395a1cccd059397042a8884e0e62/src/sortingtraining/sortalgorythms/SortTest.java#L9

**Comment by pawelKapl** [comment]
Passed!

**Comment by Augustyn** [comment]
I've added trivial assert, because JDK one may be disabled, and it seems that it was disabled at my version. Please try to run it again. Not all cases covered

**Comment by darkonion** [comment]
Passed!

**Comment by pawelKapl** [comment]
Okay, with a bit of trouble, but test passed! Thanks to it, it turned out that BucketSort had a bug. Now it is fixed. 

To pass this test i was forced to add additional condition to each sorting class, stating that if size of array is below 2, it should just return array without any changes. Hope that it is not a cheat, cause i was forced to locate this condition after copying array function to give  it a different memory address :) 

BTW. And yeah... You proved me that trying to fix it on Array Generator lvl is pointless from each single sorting class POV ! Definately sorting algorithm should be able to take care of this situation by itself.

**Comment by Augustyn** [comment]
ok
